# HarID portal attributes
portal_hostname: harid.ee
portal_port: 443

# In order to get api_user and secret, please login to harid.ee and follow setup guide:
# Guide in English: https://harid.ee/docs/en/how_to_manage_api_users_for_harid_ad_ldap_sync.html
# Juhend eesti keeles: https://harid.ee/docs/et/kuidas_lisada_api_kasutaja_harid_ad_ldap_andmevahetuseks.html
api_user: SomEu5eR
secret: SecretTok3n

# Your LDAP server connection setup (hint: usual ldap server ports are 389, 636)
ldap_host: localhost
ldap_port: 636

# whether to use :ssl, :tls, or :plain (unencrypted)
ldap_method: :ssl

# 'ldap_base' is where you search for users, groups etc.
ldap_base: DC=example,DC=com

# 'ldap_bind_dn' is the user on the LDAP server permitted to overwrite the LDAP directory within the defined search base.
ldap_bind_dn: cn=admin,dc=example,dc=com

# 'ldap_password' is the password for the bind_dn user.
ldap_password: testtest

# NB! Before you can enable HarIDSync utility you must first login to HarID
# and authorize (aka copy-paste) your newly generated public key in HarID portal. 
# HarIDSync utility is disabled by default.
# Please comment in following line if you want to activate HarIDSync utility. Just remove first character '#':

# haridsync_enabled: true
